import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import MainHeader from "@/components/Headers/MainHeader";
import MainFooter from "@/components/Foters/MainFooter";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "net-truyen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-[#ebebeb] mx-auto" lang="en">
     <body className={inter.className}>{children}</body>
    </html>
  );
}
